### PR TITLE
Update config.guess and config.sub

### PR DESCRIPTION
**Pull request by leskin-in**
Update `config.guess` and `config.sub` to support new architectures.

This is similar to https://github.com/greenplum-db/gpdb/commit/15161602f78d47e7c192caa1966aec86cb50eee9.

### CODE REVIEW

**Comment by zql19843** [comment]
怎样操作更新

**Comment by zql19843** [comment]
> 更新`config.guess`并`config.sub`支持新架构。
> 
> 这类似于[greenplum-db / gpdb @ 1516160](https://github.com/greenplum-db/gpdb/commit/15161602f78d47e7c192caa1966aec86cb50eee9)。

还是不行啊
我执行 ../configure --prefix=/usr/local 还是报错
image
[root@slave2 build]# ../configure --prefix=/usr/local
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether to use rpath... yes
checking for g++... g++
checking whether the C++ compiler works... no
configure: error: in `/root/gp-xerces/build':
configure: error: C++ compiler cannot create executables
See `config.log' for more details

**Comment by leskin-in** [comment]
@zql19843 , I think your problem is of different kind than the one that this PR deals with. See https://stackoverflow.com/questions/43359860/configure-error-c-compiler-cannot-create-executables for example.

**Comment by leskin-in** [comment]
Closing this as GPDB is now using non-patched Xerces.

**Pull request closed without merging**
